Ontotext-AD/terraform-azure-graphdb

- main.tf
- modules/configuration/README.md
- modules/configuration/main.tf
- modules/configuration/variables.tf
- modules/configuration/versions.tf
- modules/identity/README.md
- modules/identity/main.tf
- modules/identity/output.tf
- modules/identity/variables.tf
- modules/identity/versions.tf
- modules/load_balancer/main.tf
- modules/vault/README.md
- modules/vault/main.tf
- modules/vault/output.tf
- modules/vault/variables.tf
- modules/vault/versions.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
- modules/vm/variables.tf
- variables.tf
Updated the user data script to authenticate in Azure CLI and download the license.
Added new TF modules:
- configuration - takes care of handling GraphDB configurations and secrets
- identity - responsible for creating and managing a user assigned identity
- vault - creates a key vault for storing sensitive configurations
> TES-309: Support for loading GraphDB license in VMSS

- main.tf
- modules/configuration/main.tf
- modules/configuration/variables.tf
- modules/configuration/versions.tf
- modules/vm/README.md
- modules/vm/templates/entrypoint.sh.tpl
- variables.tf
- Added optional cluster token configuration (if empty, it generates a random secret)
- Added insertion of additional optional graphdb.properties configurations
- Added optional GraphDB environment variables configurations
> TES-304: Added configuration overrides for GraphDB

- .terraform.lock.hcl
- main.tf
- modules/configuration/main.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
- modules/vm/variables.tf
- variables.tf
Added script which, creates and attaches volumes
The script covers the following scenarios: 
* No disk in AZ - creates and attaches
* Existing disk in AZ - attaches. 
* 2 instance in one AZ - creates and attaches, if only one disk is present it will create a new one for the new VM instance. 
TES-330
Added attach volume script to the entrypoint.sh.tpl
N/A
> Added script which, creates and attaches volumes

- main.tf
- modules/address/main.tf
- modules/address/outputs.tf
- modules/address/variables.tf
- modules/bastion/README.md
- modules/bastion/main.tf
- modules/bastion/variables.tf
- modules/configuration/main.tf
- modules/configuration/variables.tf
- modules/gateway/main.tf
- modules/gateway/variables.tf
- modules/identity/main.tf
- modules/identity/output.tf
- modules/identity/variables.tf
- modules/tls/main.tf
- modules/tls/outputs.tf
- modules/tls/variables.tf
- modules/vault/main.tf
- modules/vault/output.tf
- modules/vault/variables.tf
- modules/vm/main.tf
- modules/vm/variables.tf
Data sources are used when a resource is managed outside the current Terraform.
- Replaced data sources with the needed identifier variables
- Removed incorrect depends_on
- Minor code organization and comment updates for consistency
> TES-307: Removed data sources

- main.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
- modules/vm/variables.tf
- variables.tf
Updated the disks to PremiumSSD_v2
TES-330
Changed the disks to PremiumSSD_v2
Added variables for IOPS and throughput 
N/A
> TES-330 Updated the disks to PremiumSSD_v2

- main.tf
- modules/address/outputs.tf
- modules/nat/README.md
- modules/nat/main.tf
- modules/nat/outputs.tf
- modules/nat/variables.tf
- modules/nat/versions.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
Added NAT gateway for outbound connectivity from GraphDB's VMSS subnet.
- Added new nat module that will create single zone NAT gateway
- Disabled public IP for GraphDB's VMSS instances
- Removed internet connectivity check in the user data script
- Added additional output variables in the address module
> TES-350: Added NAT gateway

- .terraform.lock.hcl
- main.tf
- modules/backup/main.tf
- modules/backup/outputs.tf
- modules/backup/variables.tf
- modules/backup/versions.tf
- modules/configuration/main.tf
- modules/configuration/variables.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
- modules/vm/variables.tf
- variables.tf
Added a Terraform `backup module`for Azure GraphDB.
https://ontotext.atlassian.net/browse/TES-303
Added `backup module` that includes:
1. - `main.tf`
2. - `outputs.tf`
3. - `README.MD`
4. - `variables.tf`
5. - `versions.tf`
I have included the backup module in `main.tf`and the needed variables in `variable.tf`.
> TES-303 backup module

- main.tf
- modules/backup/main.tf
- modules/backup/outputs.tf
- modules/backup/variables.tf
- modules/configuration/main.tf
- modules/configuration/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- modules/vm/main.tf
- Added key vault service endpoints to the gateway and vmss subnets
- Configured the key vault with NACLs to restrict the access only to the virtual network and given management CIDRs
- Fixed the graphdb password configuration secret to reference the correct value
- Organized the backup module
- Added the resource name prefix to the custom roles to avoid clashes
> TES-358: Added Key Vault NACLs

- .github/workflows/ci.yml
- .trivyignore
- README.md
- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/configuration/main.tf
- modules/gateway/main.tf
- modules/gateway/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
- modules/vm/variables.tf
- trivy.yaml
- variables.tf
Cleaned up issues reported by tflint, tfsec, Trivy and Checkov.
- Added content type for the key vault secrets
- Disabled VMSS password login
- Enabled VMSS encryption at rest
- Added networking rules for the storage account to limit the access only from the VMSS subnet and management CIDRs
- Changed the default storage account redundancy to ZRS (multi zonal)
- Added the latest recommended SSL policy profile
- Disabled the public access to the managed disks
- Enabled encryption at host for the VMs
- Added configurations for key vault purge protection
- Disabled the ability for storage blobs to become public
- Variables formatting
- Replaced tfsec with trivy in the GitHub workflow
> TES-363: Cleaned up configuration and security issues

- .github/workflows/ci.yml
- main.tf
- modules/backup/main.tf
- modules/backup/outputs.tf
- modules/backup/variables.tf
- modules/configuration/main.tf
- modules/identity/variables.tf
- modules/roles/README.md
- modules/roles/main.tf
- modules/roles/variables.tf
- modules/tls/main.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
- modules/vm/variables.tf
TES-359: Role assignments overhaul
The overhaul focuses on simplifying the module dependencies and responsibilities.
- Vault and backup modules no longer depend on an identity
- Added a new module rules dedicated for role assignments to anything required by the VMSS such as the key vault and backup storage account
- Moved custom roles to the new roles module
- Removed the storage account custom role in favor of directly providing the storage container in the user data script
- Removed useless empty BLOB creation in the storage account
- Optimized configurations role assignments for least privilege
- Updated some comments/descriptions
> TES-359: Fine tune role assignments

- README.md
- main.tf
- modules/appconfig/main.tf
- modules/appconfig/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- variables.tf
Instead of assigning the current user as data owner or administrator, it's better to assign a security group.
- Added optional configuration `admin_security_principle_id`
- Removed `assign_data_owner_roles` configuration
- Reverted wrongly reverted empty file
> TES-432: Use service principle for KV and App Config

- main.tf
- modules/bastion/main.tf
- modules/vmss/main.tf
- modules/vmss/variables.tf
The rules further restrict the network communication between the subnets.
- Added Application Security Group for GraphDB VMSS
- Restricted Bastion NSGs rules
- Restricted App Gateway NSG inbound rules
- Restricted the VMSS NSG rules
- Inbound is allowed only from App Gateway and Bastion
- Outbound is allowed only for internet access
> TES-393: Added additional NSGs rules

- README.md
- main.tf
- modules/graphdb/main.tf
- modules/graphdb/variables.tf
- variables.tf
It's easier to reference GraphDB from the marketplace without building any resource ID, and it makes more sense to route it through there so users can accept the terms.
Additionally:
- Updated to GraphDB 10.6.0
> TES-461: Switch to Marketplace offer as image source

- README.md
- main.tf
- modules/graphdb/identity.tf
- modules/graphdb/variables.tf
- modules/tls/outputs.tf
- variables.tf
Add option for TLS from External Key Vault under the same tennant
Made changes so that IF provided variables for `tls_manage_id` or/and `tls_certificate` it will use them instead of the ones created by Terraform. 
TES-439
https://ontotext.atlassian.net/browse/TES-439
> Add option for TLS from External Key Vault under the same tennant

- .terraform.lock.hcl
- README.md
- main.tf
- modules/appconfig/main.tf
- modules/appconfig/variables.tf
- modules/gateway/main.tf
- modules/gateway/pip.tf
- modules/gateway/variables.tf
- modules/graphdb/nat.tf
- modules/graphdb/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- variables.tf
- versions.tf
Added idle timeout variable for App GW PIP and NAT GW PIP
Fixed type-o
Added graphdb_external_address_fqdn variable to provide already available domain name
Disabled Application Gateway global proxy buffer by default.
Bumped required Terraform version to 1.7.4.
Added azurerm_monitor_diagnostic_setting to Application Config
Migrated Key Vault diagnostic settings to use Log Analytics workspace instead of the storage account as it will be deprecated.
GDB-9640
Added idle timeout variable for App GW PIP and NAT GW PIP
Fixed type-o
Added graphdb_external_address_fqdn variable to provide already available domain name
N/A
> GDB-9640 Added idle timeout variable for App GW PIP and NAT GW PIP

- CHANGELOG.md
- README.md
- main.tf
- modules/appconfig/main.tf
- modules/appconfig/variables.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- provider.tf
- variables.tf
- Added soft delete configurations for the storage account
- Added example in the readme for configuring purge protection and soft delete policies
- Bumped GraphDB to version 10.6.1
- Renamed some variables to follow a better naming convention
- Added configuration for the storage account's copy rule
- Added configuration for the storage account's max days lifecycle
https://ontotext.atlassian.net/browse/GDB-9626
> GDB-9626: Purge protection and soft delete options

- .terraform.lock.hcl
- README.md
- main.tf
- modules/appconfig/main.tf
- modules/appconfig/variables.tf
- modules/graphdb/identity.tf
- modules/graphdb/main.tf
- modules/graphdb/templates/00_wait_resources.sh.tpl
- modules/graphdb/templates/02_dns_provisioning.sh.tpl
- modules/graphdb/templates/03_gdb_conf_overrides.sh.tpl
- modules/graphdb/templates/07_cluster_setup.sh.tpl
- modules/graphdb/user_data.tf
- modules/monitoring/diagnostic_settings.tf
- modules/monitoring/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- provider.tf
- variables.tf
- Added a new user data script that will wait for services and resources on which the GraphDB deployment depends
- Updated the existing user data scripts to accept the concrete resource names instead of querying them from az CLI
- Removed unused variable i nthe monitoring sub module
- Added handling when the monitoring is disabled
https://ontotext.atlassian.net/browse/GDB-9698
> GDB-9698: Wait for resources in the user data script

- main.tf
- modules/monitoring/diagnostic_settings.tf
- modules/monitoring/variables.tf
Changed key_vault_diagnostic_settings to be deployed only if vault module is deployed
GDB-9903
Changed key_vault_diagnostic_settings to be deployed only if vault module is deployed
N/A
> Changed key_vault_diagnostic_settings to be deployed only if vault module is deployed

- modules/graphdb/templates/01_disk_management.sh.tpl
Some VMs come with an sr0 device mounted at LUN2 which makes the userdata script break because it's not the mounted disk we expect. Fixed this by adding filtering for cd/dvd devices. 
Added filtering for cd/dvd devices
> Fixed and issue with detecting cd/dvd device as gdb disk device

- CHANGELOG.md
- main.tf
- modules/monitoring/diagnostic_settings.tf
- modules/monitoring/variables.tf
Fixed the deployment of key vault diagnostic settings when monitoring is enabled
GDB-10224
Introduced new variable `create_key_vault_diagnostic_settings`
N/A
> GDB-10224 Fixed the deployment of key vault diagnostic settings when monitoring is enabled

- CHANGELOG.md
- README.md
- main.tf
- modules/graphdb/user_data.tf
- modules/graphdb/variables.tf
- variables.tf
Implemented a mechanism to include additional user data scripts. 
Custom shell scripts can now be supplied via the user_supplied_scripts variable.
The scripts should be provided in a list, and they will be executed in the order they appear in the list.
GDB-10230
Added dynamic part to the `cloudinit_config` and `user_supplied_scripts` variable accepting a list.
N/A
> Introduced mechanism to provide additional user data scripts

- CHANGELOG.md
- README.md
- main.tf
- modules/graphdb/main.tf
- modules/graphdb/variables.tf
- variables.tf
Ensure the VMSS will always be able to resolve addresses in the Private DNS Zone
This handles cases where the VNet has custom DNS servers set. 
GDB-10042
Added the MS internal DNS to be the default DNS for the VMSS.
> GDB-10042 Ensure the VMSS will always be able to resolve addresses in the Private DNS Zone

- CHANGELOG.md
- README.md
- main.tf
- modules/gateway/main.tf
- modules/gateway/variables.tf
- modules/graphdb/disks.tf
- modules/graphdb/main.tf
- modules/graphdb/templates/00_functions.sh
- modules/graphdb/templates/02_disk_management.sh.tpl
- modules/graphdb/templates/08_cluster_setup.sh.tpl
- modules/graphdb/templates/09_cluster_join.sh.tpl
- modules/graphdb/templates/10_start_single_graphdb_services.sh.tpl
- modules/graphdb/user_data.tf
- modules/monitoring/availability_tests.tf
- modules/monitoring/variables.tf
- variables.tf
Introduced ability for single node deployment
GDB-10401
* Support for single node deployment:
* If `node_count` is 1 and multiple availability zones are specified, only the first AZ will be used.
* Updated Monitoring module to dynamically adjust properties based on node_count.
* Updated Gateway module to dynamically adjust properties based on node_count.
* For `node_count` of 1, no disk is created beforehand; the disk is created by the userdata scripts.
* Made cluster-related userdata scripts executable only when node_count is greater than 1.
* Added new userdata script `10_start_graphdb_services.sh.tpl` for single node setup.
N/A
> Introduced ability for single node deployment

- CHANGELOG.md
- main.tf
- modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
- modules/graphdb/user_data.tf
Fixed the `graphdb.external-url` value when deploying a single node.
GDB-10524
* Fixed the `graphdb.external-url` value when deploying a single node.
* Changed to create `graphdb-cluster-proxy/graphdb.properties` only when `node_count` > 1
> Fixed the `graphdb.external-url` value when deploying a single node

- README.md
- variables.tf
Added missing default for `tls_certificate_path`
GDB-10857
Added default for `tls_certificate_path`
> Added missing default for tls_certificate_path

- README.md
- modules/monitoring/alerts.tf
- modules/monitoring/variables.tf
In this pull request, I have implemented a bug fix to conditionally create the azurerm_role_assignment resource based on the value of monitor_reader_principal_id.
GitHub issue: #99 
Internal Jira Issue: [GDB-11331](https://ontotext.atlassian.net/browse/GDB-11331)
Added a conditional expression using the [count](https://developer.hashicorp.com/terraform/language/meta-arguments/count) meta-argument to ensure the azurerm_role_assignment resource is only created if monitor_reader_principal_id is not null.
No
[GDB-11331]: https://ontotext.atlassian.net/browse/GDB-11331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GDB-1133 Fix handling for Monitor Reader Principal ID being null

- .github/workflows/ci.yml
- main.tf
- modules/graphdb/templates/00_functions.sh
- modules/graphdb/templates/01_wait_resources.sh.tpl
- modules/graphdb/user_data.tf
- Fixed Resource Management lock
- Added Wait condition for DNS Records and nodes
[GDB-11403]
- Fixed Resource Management lock
- Added Wait condition for DNS Records and nodes
[GDB-11403]: https://ontotext.atlassian.net/browse/GDB-11403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added DNS Wait condition and fixed Resource Lock

- modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
- outputs.tf
* Changed the run backup script to accept storage account and container as variables instead of being hardcoded.
* Removed output `app_configuration_endpoint` as it's not used.
N/A
* Changed the run backup script to accept storage account and container as variables instead of being hardcoded.
* Removed output `app_configuration_endpoint` as it's not used.
N/A
> Changes to the run backup script configuration

- CHANGELOG.md
- outputs.tf
Removed duplicated public_address output in outputs.tf
Removed duplicated public_address output in outputs.tf
> Removed duplicated public_address output in outputs.tf

- .terraform.lock.hcl
- CHANGELOG.md
- README.md
- main.tf
- modules/backup/main.tf
- modules/gateway/outputs.tf
- modules/graphdb/main.tf
- modules/monitoring/availability_tests.tf
- modules/monitoring/variables.tf
- outputs.tf
- provider.tf
- variables.tf
- versions.tf
- Updated AzureRM provider to version 4.17
- Added changes regarding the provider update
- Added changes to output private_ip_address of the Application Gateway when deployed in private mode.
- Updated CHANGELOG.md
- Changed storage_account_name to storage_account_id in modules/backup/main.tf since it will be removed in version 5.0 of the Provider.
-  Updated AzureMonitorLinuxAgent extension for the VMSS to from 1.0 to 1.33
- Disabled availability tests in the monitoring module if Application Gateway is deployed in private mode.
[GDB-11597]
- Updated AzureRM provider to version 4.17
- Added changes regarding the provider update
- Added changes to output private_ip_address of the Application Gateway when deployed in private mode.
- Updated CHANGELOG.md
- Changed storage_account_name to …
> [GDB-11597]Update the terraform module to set the private frontend IP as a external FQDN and update provider version

- modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
Parses GDB_JAVA_OPTS variable from /etc/graphdb/graphdb.env, instead of source the file
[GDB-11833](https://ontotext.atlassian.net/browse/GDB-11833)
Changes `04_gdb_conf_overrides.sh.tpl` to parse `/etc/graphdb/graphdb.env` and modify GDB_JAVA_OPTS inline  
[GDB-11833]: https://ontotext.atlassian.net/browse/GDB-11833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-11833] Parse /etc/graphdb/graphdb.env and modify GDB_JAVA_OPTS inline

- modules/graphdb/templates/06_telegraf_conf.sh.tpl
Prevents users (other from root) from reading telegraf configuration files. This is to prevent users from reading the GDB admin password, stored in the config file. 
[GDB-11815](https://ontotext.atlassian.net/browse/GDB-11815)
Sets the access permissions for the `/etc/telegraf` directory to only allow read-write by root
[GDB-11815]: https://ontotext.atlassian.net/browse/GDB-11815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-11815] Remove read/write permissions on /etc/telegraf directory

- .terraform.lock.hcl
- README.md
- modules/graphdb/config.tf
- modules/graphdb/templates/01_wait_resources.sh.tpl
- modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
- modules/graphdb/templates/08_cluster_setup.sh.tpl
- modules/graphdb/user_data.tf
- modules/graphdb/variables.tf
Changed the user data scripts so they don't trigger a refresh on existing cluster nodes when scaling out, preventing downtime.
GDB-12121 
Added a new property in Application config named `node_count` and changed the user data scripts to read the node count from it. 
As a result scaling from 1 to 3 nodes works as expected, scaling from 3 to 5 or more nodes does not introduce downtime.
N/A
> [GDB-12121] Changed the user data scripts so they don't trigger a refresh during scale out

- modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
- modules/graphdb/user_data.tf
Removes /etc/sudoers.d/90-cloud-init-users to remove sudo capability from graphdb and packer users
[GDB-11814](https://ontotext.atlassian.net/browse/GDB-11814)
Removes /etc/sudoers.d/90-cloud-init-users
[GDB-11814]: https://ontotext.atlassian.net/browse/GDB-11814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-11814] Remove sudoers.d/90-cloud-init-users

- modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
Creates a new OS-level user, `gdb-backup` for the purpose of creating the backups and access to `az-cli`. Remove access to `az` for any other user
[https://graphwise.atlassian.net/browse/GDB-11816](GDB-11816)
Creates a new OS-level user, `gdb-backup` for the purpose of creating the backups and access to `az-cli`. Remove access to `az` for any other user
> [GDB-11816] Create gdb_backup user for backups (access to cli as well)

- modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
Fixes gdb-backup backup user
[https://graphwise.atlassian.net/browse/GDB-11816](GDB-11816)
Fix to gdb-backup user creation - create home directory (need by `az-cli`)
> Create backup user home directory, otherwise az cli fails

- CHANGELOG.md
- README.md
- main.tf
- modules/gateway/variables.tf
- modules/graphdb/variables.tf
- variables.tf
Added configurable option  **app_gateway_pip_idle_timeout** that allows manipulation of the frontend public IP (PIP) timeout for the Azure Application Gateway and **nat_gateway_pip_idle_timeout** that allows manipulation of the frontend public IP (PIP) timeout for the Azure NAT Gateway.
- [✅] I have tested these changes thoroughly.
- [✅] My code follows the project's coding style.
- [✅] I have added appropriate comments to my code, especially in complex areas.
- [✅] All new and existing tests passed locally.
> Added variable for setting the Application Gateway Public IP idle timeout
