Ontotext-AD/terraform-azure-graphdb

- main.tf
- modules/configuration/variables.tf
- modules/image/README.md
- modules/image/main.tf
- modules/image/output.tf
- modules/image/variables.tf
- modules/image/versions.tf
- modules/load_balancer/variables.tf
- modules/vm/main.tf
- modules/vm/variables.tf
- variables.tf
- Added network related configuration variables
- Created image module for resolving the image ID
- Added support for custom user data script
- Fixed zone configurations in the VM module
- Added some (semi)useful comments in the modules for clarity
- Ordered the configuration variables
> TES-335: Module Improvements

- modules/configuration/main.tf
- modules/vm/main.tf
- modules/vm/templates/entrypoint.sh.tpl
Reduced the permissions given to create/attach volumes with a custom role.
Moved the permissions to the VM module
TES-351
Reduced the permissions given to create/attach volumes with a custom role.
Moved the permissions to the VM module
N/A
> Reduced the permissions given to create/attach volumes

- main.tf
- modules/bastion/main.tf
- modules/bastion/variables.tf
- modules/bastion/versions.tf
- variables.tf
Added Bastion module
TES-347
Added Bastion module
N/A
> Added Bastion Module

- CONTRIBUTING.md
- README.md
- main.tf
- provider.tf
- terraform-docs.yaml
- Added generic CONTRIBUTING.md guide that we use in the other repositories
- Added the following sections in the README
  - Short introduction about the module + TOC
  - Key features
  - Configurations
  - Example usage and deployment
- Moved the provider block to a separate file provider.tf
> TES-367: Document the Terraform module

- modules/user-data/templates/entrypoint.sh.tpl
- modules/vmss/main.tf
Handled several race conditions and issues with the userdata script
TES-396
Added --resource-group to DISKS_IN_ZONE
Added check if disk is available and retry
Changed check GDB endpoint
Moved chown to be executed only if the disk is mounted
N/A
> Handled several race conditions and issues with the userdata script

- modules/roles/main.tf
- modules/user-data/templates/entrypoint.sh.tpl
Removed managed_disk_manager role in favor of built in role
TES-411
Removed managed_disk_manager role in favor of built in role
Added additional logging
N/A
> TES-411: Removed managed_disk_manager role in favor of built in role

- main.tf
- modules/user-data/templates/entrypoint.sh.tpl
- modules/vault/main.tf
- modules/vault/variables.tf
- modules/vmss/main.tf
TES-384 Added monitoring for Key Vault
TES-386 Added AzureMonitorLinuxAgent
TES-404 Added Telegraf and exposed Prometheus metrics to Monitoring
TES-384 TES-386  TES-404 
Added monitoring for Key Vault
Added AzureMonitorLinuxAgent
Added Telegraf and exposed Prometheus metrics to Monitoring
> Added Monitoring

- modules/user-data/templates/entrypoint.sh.tpl
Fixed an issue with disk not created due to race condition
N/A
Added retry if disk is not available after attach operation
N/A
> Fixed an issue with disk not created due to race condition

- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- variables.tf
TES-369
- Added new storage rule that transfers block blobs from hot to cool
- Added variable for overriding the default retention period of 3 days
[TES-369](https://ontotext.atlassian.net/browse/TES-369)
[TES-369]: https://ontotext.atlassian.net/browse/TES-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TES-369: Added rule to change storage class tiers

- main.tf
- modules/user-data/main.tf
- modules/user-data/templates/entrypoint.sh.tpl
- modules/user-data/variables.tf
**This is to be merged after GraphDB 10.5 is released**
Updated the backup script to use the cloud-backup endpoint
N/A
Updated the backup script to use the cloud-backup endpoint
Added retry mechanism
N/A
> TES-344 Updated the backup script to use the cloud-backup endpoint

- modules/user-data/templates/entrypoint.sh.tpl
Fixed issue with assigning same IP to multiple DNS records when multiple nodes were starting
TES-422
Added check if the current instance IP is already assigned to a record in the private DNS then it will not try to reassign it as the addresses are all in the same subnet. This way if we have instances with IPs:  10.2.0.4, 10.2.0.5, 10.2.0.6 and a rolling upgrade is performed the addresses will remain the same only if a new address is present e.g., 10.2.0.8 then the script will attempt to figure out which node is missing and update the IP in the DNS. 
N/A
> Fixed issue with assigning same IP to multiple DNS records

- README.md
- main.tf
- modules/user-data/main.tf
- modules/user-data/templates/entrypoint.sh.tpl
- modules/user-data/variables.tf
- modules/vmss/main.tf
- modules/vmss/variables.tf
- variables.tf
Added creation of managed disks.
TES-377
Added creation of managed disks for the VMSS instances
Moved disk defaults to root variables
Added variables for previously hardcoded values
N/A
> TES-377 Added creation of managed disks for the VMSS instances

- README.md
- main.tf
- modules/monitoring/main.tf
- modules/monitoring/output.tf
- modules/monitoring/variables.tf
- modules/user-data/main.tf
- modules/user-data/templates/06_application_insights_config.sh.tpl
- modules/user-data/variables.tf
- variables.tf
Reduced the metrics we gather to optimize the cost
Fixed an issue with Max Heap used alert
TES-468
- Reduced the metrics we gather to optimize the cost
- Fixed an issue with Max Heap used alert
- Added overrides to the application insights config file reducing the amount of data being ingested
- Added role name for the application insights agents
- Added new variables for sampling and log level
- Fixed an issue with the Max Heap Memory Used alert
- Reduced the metrics we gather to optimize the cost
- Added overrides to the application insights config file reducing the amount of data being ingested
- Added role name for the application inssights agents
- Added new variables for sampling and log level
- Added daily_quota_gb limit of 1GB to the log analytics workspace
- Added variables for …
> TES-468 Reduced the metrics we gather to optimize the cost

- .gitignore
- .terraform.lock.hcl
- README.md
- main.tf
- modules/gateway/main.tf
- modules/gateway/outputs.tf
- modules/gateway/variables.tf
- output.tf
- variables.tf
Added private link service functionality to the application gateway
- Created private link service definition to the application gateway module
- Reorganized blocks related to the configuration for the public frontend configuration and the private frontend configuration to add a toggle to disable/enable configurations. For example, to deploy application gateway in private mode only or in public mode only.
- Added a new subnet for the private link service
- Added new variables related to the private link service
> TES-446: Added Private Link Service functionality for the application gateway

- main.tf
- modules/gateway/nsg.tf
- modules/graphdb/disks.tf
- modules/graphdb/templates/01_disk_management.sh.tpl
- modules/graphdb/user_data.tf
- modules/monitoring/main.tf
- modules/monitoring/variables.tf
- output.tf
- Updated the naming of managed disks to avoid the rg- prefix from the RG name
- Fix the deployment without monitoring being enabled
- Updated public_address_fqdn to print a whole URL
- Added NSG for the private link subnet
- Updated the naming of monitoring resources to use the resources name prefix instead of the resource group name
> TES-337: Minor tweaks and updates

- .terraform.lock.hcl
- README.md
- main.tf
- modules/graphdb/main.tf
- modules/graphdb/templates/01_disk_management.sh.tpl
- modules/graphdb/templates/02_dns_provisioning.sh.tpl
- modules/graphdb/templates/06_application_insights_config.sh.tpl
- modules/graphdb/templates/07_cluster_setup.sh.tpl
- modules/graphdb/variables.tf
- modules/monitoring/main.tf
- modules/monitoring/variables.tf
- variables.tf
Added fix for disk_public_network_access variable
Added new alert for low-disk-space
Changed the ASG health endpoint to use /rest/cluster/node/status
Added script which updates the GDB password if changed in application config.
Fixed an issue when determining the lowest instance ID 
N/A
Added fix for disk_public_network_access variable
Added new alert for low-disk-space
Changed the ASG health endpoint to use /rest/cluster/node/status
Added script which updates the GDB password if changed in application config.
Fixed an issue when determining the lowest instance ID
N/A
> Added alert for low-disk-space

- .terraform.lock.hcl
- main.tf
- modules/monitoring/main.tf
- modules/monitoring/variables.tf
Replaced owner notifications with email notifications in the AG
TES-485
Replaced owner notifications with email notifications in the AG
N/A
>  TES-485 Replaced owner notifications with email notifications in the AG

- modules/graphdb/templates/07_cluster_setup.sh.tpl
- modules/graphdb/templates/08_cluster_rejoin.sh.tpl
- modules/graphdb/user_data.tf
The added script introduces measures to address potential Azure outage scenarios. Specifically, it includes functionality to handle nodes that may be missing their raft folder.
TES-395 
Added new script template 08_cluster_rejoin.sh.tpl
N/A
> TES-395 Added handling AZ outage scenarios

- README.md
- variables.tf
Changed Application Gateway proxy buffer to be enabled by default
N/A
* Changed gateway_global_request_buffering_enabled and gateway_global_response_buffering_enabled to true by default
N/A
> Changed Application Gateway proxy buffer to be enabled by default

- main.tf
- modules/graphdb/variables.tf
Remove unused variable
N/A
Removed app_configuration_name from main.tf and graphdb module
N/A
> Remove unused variable

- CHANGELOG.md
- README.md
- variables.tf
- Added more deployment examples
- Bumped GraphDB to 10.6.2
https://ontotext.atlassian.net/browse/GDB-9624
> GDB-9624: Preparations for release 1.0.0

- modules/graphdb/templates/03_gdb_conf_overrides.sh.tpl
Fixed the graphdb.env appending of properties.
N/A
Fixed the graphdb.env appending of properties.
N/A
> Fixed the graphdb.env appending of properties.

- modules/graphdb/templates/02_dns_provisioning.sh.tpl
- modules/graphdb/templates/07_cluster_setup.sh.tpl
- modules/graphdb/templates/08_cluster_join.sh.tpl
Fixed issue with DNS address assignment and updated user data scripts overviews 
- Updated scripts overviews
- Added additional logging
- Fixed an issue with the DNS records when scaling out. 
- Removed logic to join the cluster if raft folder is present but empty.
N/A
> Fixed issue with DNS address assignment and scripts overviews

- .terraform.lock.hcl
- CHANGELOG.md
- modules/graphdb/identity.tf
- modules/graphdb/templates/00_functions.sh
- modules/graphdb/templates/01_wait_resources.sh.tpl
- modules/graphdb/templates/02_disk_management.sh.tpl
- modules/graphdb/templates/03_dns_provisioning.sh.tpl
- modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
- modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
- modules/graphdb/templates/06_telegraf_conf.sh.tpl
- modules/graphdb/templates/07_application_insights_config.sh.tpl
- modules/graphdb/templates/08_cluster_setup.sh.tpl
- modules/graphdb/templates/09_cluster_join.sh.tpl
- modules/graphdb/user_data.tf
We had a problem with VMs stealing the disks from each other and one more VM could end up without an attached data disk.
This PR contains fixes for the disk creation as well as logging improvements.
GDB-10281
Improved logging for all data scripts. 
Refactored 02_disk_management.sh.tpl
N/A
> GDB-10281 Fix volume creation for 3+ node cluster

- main.tf
Fixed ssh_key reading
N/A
N/A
N/A
> Fixed ssh_key reading

- .terraform.lock.hcl
- README.md
- main.tf
- variables.tf
Added support to deploy with existing RG and Vnet
GDB-9710 
Added support to deploy with existing RG and Vnet
N/A
> GDB-9710 Added support to deploy with existing RG and Vnet

- README.md
During my tests of the Azure module, I discovered that the command stated for accepting the offer in the Azure MarketPlace in the README will be deprecated in the next version of the Azure CLI. So I suggest updating our documentation so everything is up to date
Changed Azure CLI command for accepting the offer in the Market Place.
> Update the accept terms command in the README

- CHANGELOG.md
- README.md
- variables.tf
Bumped GraphDB version to 10.7.0
N/A
Bumped GraphDB version to 10.7.0
N/A
> Bumped GraphDB version to 10.7.0

- CHANGELOG.md
- README.md
- variables.tf
Update default version of GraphDB to 10.7.1
> update default graphdb version to 10.7.1

- CHANGELOG.md
- modules/graphdb/templates/00_functions.sh
- modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
- modules/graphdb/templates/07_application_insights_config.sh.tpl
- modules/graphdb/templates/10_start_single_graphdb_services.sh.tpl
- modules/graphdb/user_data.tf
Improved the single node setup time by removing use and checks for Private DNS zone address.
GDB-10618
- Removed the Private DNS zone when single node.
- Removed dependencies on DNS zone address when single node.
- Removed waits for DNS address availability when single node.
N/A
> GDB-10618 Improved the single node setup time by removing use and checks for Private DNS zone address.

- .terraform.lock.hcl
- CHANGELOG.md
- README.md
- variables.tf
Update default GraphDB version to 10.7.2
Update default GraphDB version to 10.7.2
> Update default GraphDB version to 10.7.2

- CHANGELOG.md
- README.md
- variables.tf
Updated GDB version to 10.7.3
N/A
Updated GDB version to 10.7.3
N/A
> Updated GDB version to 10.7.3

- CHANGELOG.md
- README.md
- variables.tf
Updated GraphDB Version to 10.7.5
Updated GraphDB Version to 10.7.5
> Updated GraphDB Version to 10.7.5

- .terraform.lock.hcl
- README.md
- variables.tf
Changed the readme to fix TLS as required instead of not. Added a note to make sure that there would be no more mistakes.
**[here](https://ontotext.atlassian.net/browse/GDB-10857)**
main readme.md
> GDB-10857-fix tls documentation

- CHANGELOG.md
- README.md
- variables.tf
Update GraphDB default version to 10.7.6
Update GraphDB default version to 10.7.6
> Update GraphDB default version to 10.7.6

- CHANGELOG.md
- README.md
- variables.tf
Update default GraphDB version to 10.8.0
Update default GraphDB version to 10.8.0
> Update default GraphDB version to 10.8.0

- main.tf
- Changed the management lock to be applied only to the resources defined in the resources _to_lock local variable.
[GDB-11332]
- Changed the management lock to be applied only to the resources defined in the resources _to_lock local variable.
[GDB-11332]: https://ontotext.atlassian.net/browse/GDB-11332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-11332] Changes to the mangement lock scope

- CHANGELOG.md
- README.md
- variables.tf
Updated default GraphDB version to 10.8.2
Updated default GraphDB version to 10.8.2
> Updated default GraphDB version to 10.8.2

- README.md
- main.tf
- modules/graphdb/user_data.tf
- modules/graphdb/variables.tf
- variables.tf
Added ability to provide additional user rendered templates and sh.tpl files
[GDB-11592]
Added ability to provide additional user rendered templates and sh.tpl files
[GDB-11592]: https://ontotext.atlassian.net/browse/GDB-11592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-11592] Added ability to provide additional user rendered templates and sh.tpl files

- CHANGELOG.md
Fix CHANGELOG.md
[GDB-11592]
Fix CHANGELOG.md
[GDB-11592]: https://ontotext.atlassian.net/browse/GDB-11592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-11592] Fix CHANGELOG.md

- CHANGELOG.md
- README.md
- variables.tf
Updated the default GraphDB VM image to the latest patch version.
> Update GraphDB to version 10.8.3

- modules/graphdb/templates/09_cluster_join.sh.tpl
Scaling up does not connect the new instance to the cluster.
When scaling up the GraphDB instances, for example, from 3 to 4 (node_count=3 → 4), the fourth machine will not join the cluster.
Jira issue: [GDB-11605](https://ontotext.atlassian.net/browse/GDB-11605)
The solution is to update the environment variable that stores the admin password, as it differs from the one used in the other scripts.
No
[GDB-11605]: https://ontotext.atlassian.net/browse/GDB-11605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GDB-11605 Fix cluster-joining on scale up

- main.tf
Added check for resource lock on the vault resource
[GDB-11763]
Added check for resource lock on the vault resource
[GDB-11763]: https://ontotext.atlassian.net/browse/GDB-11763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-11763] Added check for resource lock on the vault resource

- CHANGELOG.md
- README.md
- variables.tf
Updated the default GraphDB version to the latest patch version.
> Update GraphDB to version 10.8.4

- CHANGELOG.md
- README.md
- variables.tf
Updated the default GraphDB version to the latest patch version.
> Update GraphDB to version 10.8.5

- CHANGELOG.md
Updated the CHANGELOG.md for 1.5.0
N/A
Updated the CHANGELOG.md for 1.5.0
N/A
> Updated the CHANGELOG.md for 1.5.0

- CHANGELOG.md
- README.md
- variables.tf
Updated GraphDB to version 11.0.0
N/A
Updated GraphDB to version 11.0.0
N/A
> Updated GraphDB to version 11.0.0

- CHANGELOG.md
- README.md
- variables.tf
Updated the default GraphDB version to the latest patch version for 10.x.
> Update GraphDB to version 10.8.7

- CHANGELOG.md
- README.md
- variables.tf
Updated GraphDB version to 11.0.2
> Updated GraphDB version to 11.0.2

- CHANGELOG.md
- README.md
- variables.tf
- Updated the default GraphDB version to 10.8.9
- Updated the Terraform module to version 1.5.3
> GDB-12672: Update GraphDB version to 10.8.9

- CHANGELOG.md
- main.tf
- modules/gateway/variables.tf
- modules/graphdb/variables.tf
- variables.tf
- Bumped gdb 10.8.10
- Cherrypicked https://github.com/Ontotext-AD/terraform-azure-graphdb/pull/139 
N/A
- Bumped gdb 10.8.10
- Cherrypicked https://github.com/Ontotext-AD/terraform-azure-graphdb/pull/139 
N/A
> Bumped gdb 10.8.10

- CHANGELOG.md
- README.md
- variables.tf
Bumped GDB version to 11.1.0
N/A
Bumped GDB version to **11.1.0**
N/A
> Bumped GDB version to 11.1.0

- CHANGELOG.md
- README.md
- variables.tf
Bumped GDB version to 11.1.1
N/A
Bumped GDB version to 11.1.1
N/A
> Bumped GDB version to 11.1.1

- outputs.tf
* Add outputs regarding the application gateway and public IPs
[GDB-13131]
* Add outputs regarding the application gateway and public IPs
[ACCEME-1]: https://graphwise.atlassian.net/browse/ACCEME-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GDB-13131]: https://graphwise.atlassian.net/browse/GDB-13131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add outputs regarding application gateway and public IPs

- CHANGELOG.md
- README.md
- locals.tf
- main.tf
- modules/external_dns_records/main.tf
- modules/external_dns_records/outputs.tf
- modules/external_dns_records/private_records.tf
- modules/external_dns_records/public_records.tf
- modules/external_dns_records/variables.tf
- outputs.tf
- variables.tf
* Introduced new `external-dns-records` module for managing Azure DNS zone
[GDB-13144]
* Introduced new `external-dns-records` module for managing Azure DNS zone
[GDB-13144]: https://graphwise.atlassian.net/browse/GDB-13144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GDB-13144]Introduced new `external-dns-records` module for managing Azure DNS zone
